### ISSUE TITLE
Error with authentication

### ISSUE THREAD

**Issue by AzumLex** [camunda-community-hub/camunda-8-lowcode-ui-template#115]
Hey, I have tried to use the tasklist with a secured zeebe cluster (ZEEBE_AUTHENTICATION_MODE=identity). I filled in the credentials for the keycloak client in the application.yaml file (client id and secret) and set "enabled = true". 

My setting looks exactly like this (except the client-secret):
security.oauth2:
    enabled: true
    client:
      registration.customTaskList:
        client-id: customtasklist
        client-secret: xyxy
        authorization-grant-type: authorization_code
        scope: openid,profile
        redirect-uri: http://localhost:8080/login/oauth2/code/customTaskList
      provider.customTaskList.issuer-uri: http://localhost:18080/auth/realms/camunda-platform

When I launch the application with ./mvnw spring-boot:run, I get the error code, that it doesn't receive the bearer token.
With an unsecured cluster, it works perfectly. So I am worried that I have messed up something. I would be super if there would be a solution for that

io.grpc.StatusRuntimeException: UNAUTHENTICATED: Expected bearer token at header with key [authorization], but found nothing
        at io.grpc.Status.asRuntimeException(Status.java:537) ~[grpc-api-1.60.0.jar:1.60.0]
        at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:481) ~[grpc-stub-1.60.0.jar:1.60.0]
        at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:574) ~[grpc-core-1.60.0.jar:1.60.0]
        at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:72) ~[grpc-core-1.60.0.jar:1.60.0]
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:742) ~[grpc-core-1.60.0.jar:1.60.0]
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:723) ~[grpc-core-1.60.0.jar:1.60.0]
        at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) ~[grpc-core-1.60.0.jar:1.60.0]
        at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133) ~[grpc-core-1.60.0.jar:1.60.0]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[na:na]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[na:na]

**Comment by aabuabdou** [comment]
Any luck with this exception?
I get also "UNAUTHENTICATED: Expected bearer token at header with key [authorization], but found nothing" when trying to deploy a process using Camunda web modeler in a self-hosted helm chart toplogy
